const games = [
  {
    id: 'cyberpunk',
    title: 'Cyberpunk 2077',
    subtitle: '+ Phantom Liberty',
    year: '2020',
    genre: 'RPG',
    developer: 'CD Projekt RED',
    platforms: ['steam', 'gog', 'epic'],
    cover: null,
    tags: ['открытый мир', 'футуристика', 'dlc'],
    trailerId: '8X2kIfS6fb8',
    extraTrailers: [{ id: 'sJbexcm4Trk', label: 'Phantom Liberty' }],
    desc: 'Официальный текст. Официальной русской озвучки нет — только фанатские дубляжи (в том числе для Phantom Liberty).',
    translations: [
      { type: 'text', status: 'done', author: 'CD Projekt RED',
        name: 'Официальный перевод CDPR',
        body: '<p><strong>Что переведено:</strong> Полный текст и субтитры основной игры и Phantom Liberty.</p><p><strong>Важно:</strong> официальной русской озвучки нет — только английская (и другие языки).</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'DreamVoice', version: 'v5.3', updated: '2025-08',
        name: 'DreamVoice — Гибридный дубляж Phantom Liberty',
        body: '<p><strong>Статус:</strong> актуально на патч 2.3+</p><p><strong>Что озвучено:</strong> Полный дубляж DLC Phantom Liberty (гибрид: нейросеть и ручная доработка)</p>',
        links: '<a href="https://www.playground.ru/cyberpunk_2077/file/cyberpunk_2077_gibridnyj_dublyazh_dlya_dlc_phantom_liberty_v1_0_5_3_dreamvoice-1691775" class="btn" target="_blank" rel="noopener">Playground</a><a href="https://t.me/DreamVoiceRu" class="btn" target="_blank" rel="noopener">Telegram</a>' },
      { type: 'voice', status: 'done', author: 'SynthVoiceRu', version: 'r12', updated: '2024-03',
        name: 'Нейро-дубляж SynthVoiceRu (Phantom Liberty)',
        body: '<p><strong>Что озвучено:</strong> Нейро-дубляж DLC Phantom Liberty.</p>',
        links: '<a href="https://www.playground.ru/cyberpunk_2077/file/cyberpunk_2077_nejro_dublyazh_dlya_dlc_phantom_liberty_v2_0_0_synthvoiceru-1683699" class="btn" target="_blank" rel="noopener">Playground</a>' },
      { type: 'voice', status: 'progress', author: 'GamesVoice', version: 'сбор закрыт', updated: '2026-09',
        name: 'GamesVoice — Phantom Liberty (в работе)',
        body: '<p><strong>Статус:</strong> Сбор средств завершён, идёт производство актёрского дубляжа. Готового файла для скачивания пока нет.</p>',
        links: '<a href="https://www.gamesvoice.ru/" class="btn" target="_blank" rel="noopener">GamesVoice</a>' }
    ]
  },
  {
    id: 'bg3',
    title: "Baldur's Gate 3",
    year: '2023',
    genre: 'CRPG',
    developer: 'Larian Studios',
    platforms: ['steam', 'gog', 'ps', 'xbox'],
    cover: null,
    tags: ['dnd', 'пошаговая', 'кооператив'],
    trailerId: '1T22wNvoNiU',
    desc: 'Официальный текст. Полной профессиональной озвучки нет — есть нейросетевые варианты SynthVoiceRu.',
    translations: [
      { type: 'text', status: 'done', author: 'Larian Studios',
        name: 'Официальный перевод Larian',
        body: '<p><strong>Что переведено:</strong> Полный текстовый перевод и субтитры</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'SynthVoiceRu', version: '1.0 (SV2)', updated: '2024-12',
        name: 'SynthVoiceRu — Нейросетевой дубляж и закадр',
        body: '<p><strong>Что озвучено:</strong> Полный дубляж и отдельная закадровая версия (модель SV2)</p>',
        links: '<a href="https://www.playground.ru/baldurs_gate_3/file/baldurs_gate_3_russkaya_ozvuchka_nejrosetevoj_dublyazh_v1_0_synthvoiceru-1698229" class="btn" target="_blank" rel="noopener">Playground — дубляж</a><a href="https://www.playground.ru/baldurs_gate_3/file/baldurs_gate_3_rusifikator_zvuka_nejrosetevoj_zakadr_v1_0_synthvoiceru-1698264" class="btn" target="_blank" rel="noopener">Закадр</a>' }
    ]
  },
  {
    id: 'hogwarts',
    title: 'Hogwarts Legacy',
    year: '2023',
    genre: 'Action-RPG',
    developer: 'Avalanche Software',
    platforms: ['steam', 'ps', 'xbox'],
    cover: null,
    tags: ['гарри поттер', 'открытый мир', 'магия'],
    trailerId: '1O6Qstncpnc',
    desc: 'Полная фанатская локализация GamesVoice: текст, текстуры и озвучка.',
    translations: [
      { type: 'both', status: 'done', author: 'GamesVoice', version: '1.5', updated: '2026-09',
        name: 'GamesVoice — Полная локализация',
        body: '<p><strong>Что переведено:</strong> Текст, текстуры, полная профессиональная озвучка</p>',
        links: '<a href="https://www.playground.ru/hogwarts_legacy/file/hogwarts_legacy_rusifikator_teksta_tekstur_i_zvuka_gamesvoice-1681716" class="btn" target="_blank" rel="noopener">Playground</a><a href="https://www.gamesvoice.ru/product/hogwartslegacy" class="btn" target="_blank" rel="noopener">GamesVoice</a>' }
    ]
  },
  {
    id: 'stalker2',
    title: 'S.T.A.L.K.E.R. 2',
    subtitle: 'Heart of Chornobyl',
    year: '2024',
    genre: 'FPS / Survival',
    developer: 'GSC Game World',
    platforms: ['steam', 'xbox'],
    cover: null,
    tags: ['сталкер', 'зона', 'выживание'],
    trailerId: 'PKO4PL8Xzik',
    desc: 'Гибридные фанатские дубляжи нескольких студий.',
    translations: [
      { type: 'text', status: 'done', author: 'GSC / сообщество',
        name: 'Официальный и улучшенный текст',
        body: '<p><strong>Что переведено:</strong> Текст и субтитры</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'Eloquence / Реплика / SynthVoice / VoF', version: '2.0', updated: '2026-09',
        name: 'Гибридный дубляж (несколько студий)',
        body: '<p><strong>Что озвучено:</strong> Сборка из Eloquence Studio, Реплика, Voice of Folk и SynthVoice. Охват шире отдельных проектов; качество смешанное.</p>',
        links: '<a href="https://www.playground.ru/stalker_2/file/s_t_a_l_k_e_r_2_heart_of_chornobyl_rusifikator_zvuka_dublyazh_eloquence_studio_replika_synthvoice_vof_2_0_h-1817504" class="btn" target="_blank" rel="noopener">Playground — гибрид</a>' },
      { type: 'voice', status: 'progress', author: 'Eloquence Studio', version: 'тест', updated: '2025-10',
        name: 'Eloquence Studio — тестовая версия',
        body: '<p><strong>Что озвучено:</strong> Основной сюжет до Террикона (тестовый релиз). Участвовало 80+ актёров.</p>',
        links: '<a href="https://www.playground.ru/stalker_2/file/s_t_a_l_k_e_r_2_heart_of_chornobyl_rusifikator_zvuka_eloquence_studio-1798333" class="btn" target="_blank" rel="noopener">Playground</a>' }
    ]
  },
  {
    id: 'expedition33',
    title: 'Clair Obscur: Expedition 33',
    year: '2025',
    genre: 'JRPG',
    developer: 'Sandfall Interactive',
    platforms: ['steam', 'ps', 'xbox'],
    cover: null,
    tags: ['пошаговая', 'франция', 'сюжет'],
    trailerId: 'ejgW-upPMgk',
    desc: 'Профессиональный дубляж GamesVoice, 2026.',
    translations: [
      { type: 'both', status: 'done', author: 'GamesVoice', version: '1.5', updated: '2026-04',
        name: 'GamesVoice — Текст и озвучка',
        body: '<p><strong>Что переведено:</strong> Текст и полная профессиональная озвучка</p><p><strong>Актёры:</strong> Александр Гаврилин (Гюстав), Евгения Лучникова (Маэль), Сергей Чихачёв (Моноко) и др.</p>',
        links: '<a href="https://www.playground.ru/clair_obscur_expedition_33/file/clair_obscur_expedition_33_rusifikator_teksta_i_zvuka_v1_5_gamesvoice-1827268" class="btn" target="_blank" rel="noopener">Playground</a><a href="https://www.gamesvoice.ru/expedition33" class="btn" target="_blank" rel="noopener">GamesVoice</a>' },
      { type: 'voice', status: 'done', author: 'SynthVoiceRu', version: '2025-05', updated: '2025-05',
        name: 'SynthVoiceRu — Нейро-дубляж и закадр',
        body: '<p><strong>Что озвучено:</strong> Нейросетевой дубляж и отдельная закадровая версия. Возможны сбои липсинка.</p>',
        links: '<a href="https://www.playground.ru/clair_obscur_expedition_33/file/clair_obscur_expedition_33_rusifikator_zvuka_nejrosetevoj_dublyazh_i_zakadrovaya_ozvuchka_synthvoiceru-1769524" class="btn" target="_blank" rel="noopener">Playground</a>' }
    ]
  },
  {
    id: 'dispatch',
    title: 'Dispatch',
    year: '2025',
    genre: 'Adventure',
    developer: 'AdHoc Studio',
    platforms: ['steam', 'ps', 'xbox'],
    cover: null,
    tags: ['супергерои', 'интерактив', 'эпизоды'],
    trailerId: 'fTVgX7b1N8E',
    desc: 'Официальной русской озвучки нет. Есть русские эпизодные дубляжи NikiStudio и Studii Net, а также полный нейро-дубляж всех 8 эпизодов.',
    translations: [
      { type: 'text', status: 'done', author: 'AdHoc / сообщество',
        name: 'Официальный текст / субтитры',
        body: '<p><strong>Что переведено:</strong> Русские субтитры в игре</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'NikiStudio', version: 'Эп. 1–3', updated: '2026-07',
        name: 'NikiStudio — Эпизоды 1–3',
        body: '<p><strong>Что озвучено:</strong> Полный профессиональный дубляж эпизодов 1, 2 и 3</p><p>Работа над следующими эпизодами продолжается.</p>',
        links: '<a href="https://www.zoneofgames.ru/files/11155.html" class="btn" target="_blank" rel="noopener">Zone of Games (1–3)</a><a href="https://www.playground.ru/dispatch/file/dispatch_rusifikator_zvuka_epizod_1_nikistudio-1813525" class="btn" target="_blank" rel="noopener">Playground — эп. 1</a><a href="https://www.playground.ru/dispatch/file/dispatch_rusifikator_zvuka_epizod_2_nikistudio-1840434" class="btn" target="_blank" rel="noopener">Эп. 2</a>' },
      { type: 'voice', status: 'done', author: 'Studii Net', version: 'Эп. 1', updated: '2026-04',
        name: 'Studii Net — Эпизод 1',
        body: '<p><strong>Что озвучено:</strong> Первый эпизод, профессиональный состав</p>',
        links: '<a href="https://www.playground.ru/dispatch/file/dispatch_russkaya_ozvuchka_epizod_1_by_studii_net-1839172" class="btn" target="_blank" rel="noopener">Playground</a>' },
      { type: 'voice', status: 'done', author: 'SuddenFeliciano', version: 'v1.0.16250', updated: '2025-11',
        name: 'Нейро-озвучка — все 8 эпизодов',
        body: '<p><strong>Что озвучено:</strong> Почти все диалоги всех 8 эпизодов через нейросеть (короткие/тихие реплики могли быть пропущены фильтром)</p><p><strong>Важно:</strong> AI-перевод, возможны неточности. Качество ниже студийного дубляжа.</p>',
        links: '<a href="https://www.playground.ru/dispatch/file/dispatch_rusifikator_zvuka_v1_0_16250-1804209" class="btn" target="_blank" rel="noopener">Playground</a>' }
    ]
  },
  {
    id: 'alanswake2',
    title: 'Alan Wake 2',
    year: '2023',
    genre: 'Survival Horror',
    developer: 'Remedy Entertainment',
    platforms: ['steam', 'epic', 'ps', 'xbox'],
    cover: null,
    tags: ['хоррор', 'детектив', 'песни'],
    trailerId: 'dlQ3FeNu5Yw',
    desc: 'Официальный текст. Полный профессиональный дубляж GamesVoice, включая перепетые песни.',
    translations: [
      { type: 'text', status: 'done', author: 'Remedy',
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Текст и субтитры</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'both', status: 'done', author: 'GamesVoice', version: '1.3', updated: '2026-09',
        name: 'GamesVoice — Полный дубляж и песни',
        body: '<p><strong>Что озвучено:</strong> Полная профессиональная озвучка; песни перепеты на русском</p>',
        links: '<a href="https://www.playground.ru/alan_wake_2/file/alan_wake_2_rusifikator_teksta_i_zvuka_v1_2_gamesvoice-1765021" class="btn" target="_blank" rel="noopener">Playground</a><a href="https://www.gamesvoice.ru/alanwake2" class="btn" target="_blank" rel="noopener">GamesVoice</a>' }
    ]
  },
  {
    id: 'sh2',
    title: 'Silent Hill 2 Remake',
    year: '2024',
    genre: 'Survival Horror',
    developer: 'Bloober Team',
    platforms: ['steam', 'ps'],
    cover: null,
    tags: ['хоррор', 'психологический', 'ремейк'],
    trailerId: 'FUNVlzGwW3A',
    desc: 'Официальный текст. Полный профессиональный дубляж от GamesVoice.',
    translations: [
      { type: 'text', status: 'done', author: 'Bloober Team / Konami',
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Текст и субтитры на русском</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'GamesVoice', version: '1.1', updated: '2025-11-21',
        name: 'GamesVoice — Полный дубляж',
        body: '<p><strong>Что озвучено:</strong> Полная профессиональная озвучка ремейка. Совместимо в том числе с версией из Microsoft Store</p>',
        links: '<a href="https://www.playground.ru/silent_hill_2/file/silent_hill_2_remake_rusifikator_zvuka_gamesvoice_v1_1-1778499" class="btn" target="_blank" rel="noopener">Playground</a><a href="https://www.gamesvoice.ru/silenthill2" class="btn" target="_blank" rel="noopener">GamesVoice</a>' }
    ]
  },
  {
    id: 'kcd2',
    title: 'Kingdom Come: Deliverance II',
    year: '2025',
    genre: 'RPG',
    developer: 'Warhorse Studios',
    platforms: ['steam', 'ps', 'xbox'],
    cover: null,
    tags: ['средневековье', 'история', 'реализм'],
    trailerId: '7ynJN-HejlY',
    desc: 'Официальный текст. Нейросетевой дубляж и закадр от SynthVoiceRu — 261 тысяча реплик.',
    translations: [
      { type: 'text', status: 'done', author: 'Warhorse Studios',
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Текст и субтитры на русском</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'SynthVoiceRu', version: '09.06.2025', updated: '2025-06',
        name: 'SynthVoiceRu — Дубляж и закадр',
        body: '<p><strong>Что озвучено:</strong> Все диалоги и ролики на движке игры — 261 000 реплик. Два варианта: дубляж и закадровый перевод</p>',
        links: '<a href="https://www.playground.ru/kingdom_come_deliverance_2/file/kingdom_come_deliverance_2_rusifikator_zvuka_nejrosetevoj_perevod_v09_06_2025_synthvoiceru-1751616" class="btn" target="_blank" rel="noopener">Playground</a><a href="https://www.nexusmods.com/kingdomcomedeliverance2/mods/217" class="btn" target="_blank" rel="noopener">Nexus</a>' }
    ]
  },
  {
    id: 'rdr2',
    title: 'Red Dead Redemption 2',
    year: '2018',
    genre: 'Action / Adventure',
    developer: 'Rockstar Games',
    platforms: ['steam', 'epic', 'ps', 'xbox'],
    cover: null,
    tags: ['вестерн', 'открытый мир', 'сюжет'],
    trailerId: 'eaW0tYpxyp0',
    desc: 'Официальный текст. Актёрский фанатский дубляж в разработке — уже доступно демо.',
    translations: [
      { type: 'text', status: 'done', author: 'Rockstar Games',
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Текст и субтитры на русском</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'progress', author: 'MGVdub', version: 'демо', updated: '2026-08',
        name: 'MGVdub — дубляж (демо)',
        body: '<p><strong>Что озвучено:</strong> Демо (~120 тыс. из ~500 тыс. реплик). Миссии и часть субтитров. Проект в разработке.</p>',
        links: '<a href="https://www.playground.ru/red_dead_redemption_2/file/red_dead_redemption_2_russkaya_ozvuchka_dublyazh_demo-1866520" class="btn" target="_blank" rel="noopener">Playground — демо</a>' },
      { type: 'voice', status: 'done', author: 'SynthVoiceRu', version: '2026-09', updated: '2026-09',
        name: 'SynthVoiceRu — нейро (~425k реплик)',
        body: '<p><strong>Где скачать:</strong> По сообщениям авторов — на Boosty (дубляж и закадр). Публичной страницы файла на Playground на момент проверки не было.</p>',
        links: '<a href="https://boosty.to/synthvoiceru" class="btn" target="_blank" rel="noopener">Boosty SynthVoiceRu</a>' }
    ]
  },
  {
    id: 'gtav',
    title: 'Grand Theft Auto V',
    year: '2013',
    genre: 'Action / Open World',
    developer: 'Rockstar Games',
    platforms: ['steam', 'epic', 'ps', 'xbox'],
    cover: null,
    tags: ['открытый мир', 'кооператив', 'криминал'],
    trailerId: 'QkkoHAzjnUs',
    desc: 'Официальный текст. Фанатские озвучки сюжета существуют — качество и покрытие разные.',
    translations: [
      { type: 'text', status: 'done', author: 'Rockstar Games',
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Текст и субтитры на русском</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'SynthVoiceRu / Toreno', version: '1.0', updated: '2024-06',
        name: 'SynthVoiceRu — Нейро-дубляж (+ Enhanced)',
        body: '<p><strong>Что озвучено:</strong> Нейросетевой дубляж сюжетной линии, есть вариант Enhanced. Качество ИИ — с правками авторов.</p>',
        links: '<a href="https://www.playground.ru/gta_5/file/grand_theft_auto_5_rusifikator_zvuka_nejrosetevoj_dublyazh_enhanced_v1_0_synthvoiceru_toreno-1706326" class="btn" target="_blank" rel="noopener">Playground — дубляж</a><a href="https://www.playground.ru/gta_5/file/grand_theft_auto_5_rusifikator_zvuka_nejrosetevoj_zakadr_v1_0_synthvoiceru_toreno-1711928" class="btn" target="_blank" rel="noopener">Закадр</a>' }
    ]
  },
  {
    id: 'hl2',
    title: 'Half-Life 2',
    year: '2004',
    genre: 'FPS',
    developer: 'Valve',
    platforms: ['steam'],
    cover: null,
    tags: ['классика', 'научная фантастика', 'сюжет'],
    trailerId: 'kWnzRGD9NDE',
    desc: 'Русская озвучка Valve/Буки и community-проекты по её восстановлению и исправлению.',
    translations: [
      { type: 'text', status: 'done', author: 'Valve / Бука',
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Текст и субтитры на русском</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'Сообщество', version: '—', updated: '2025-11',
        name: 'Озвучка «Бука» (реставрация)',
        body: '<p><strong>Что озвучено:</strong> Культовая озвучка издательства «Бука» 2004 года — возвращена в игру реставрациями сообщества через Steam Workshop</p>',
        links: '<a href="https://steamcommunity.com/workshop/filedetails/?id=2995029006" class="btn" target="_blank" rel="noopener">Steam Workshop</a>' }
    ]
  },
  {
    id: 'eldenring',
    title: 'Elden Ring',
    subtitle: '+ Shadow of the Erdtree',
    year: '2022',
    genre: 'Action-RPG',
    developer: 'FromSoftware',
    platforms: ['steam', 'ps', 'xbox'],
    cover: null,
    tags: ['soulslike', 'открытый мир', 'dlc'],
    trailerId: 'E3Huy2cdih0',
    desc: 'Официальной русской озвучки нет. Стабильного полного фанатского дубляжа на 2026 не подтверждено.',
    translations: [
      { type: 'text', status: 'done', author: 'FromSoftware',
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Полный текст, включая Shadow of the Erdtree. Озвучка только английская.</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'abandoned', author: 'сообщество', version: '—', updated: '',
        name: 'Полной офлайн-озвучки нет',
        body: '<p><strong>Статус:</strong> Стабильного полного фанатского дубляжа на 2026 год не подтверждено. Встречаются разрозненные демо/эксперименты — без надёжной страницы файла не публикую ссылку.</p>',
        links: '<span class="link-muted">Ссылок нет</span>' }
    ]
  }
];
