const games = [
  {
    id: 'cyberpunk',
    title: 'Cyberpunk 2077',
    subtitle: '+ Phantom Liberty',
    year: '2020',
    genre: 'RPG',
    developer: 'CD Projekt RED',
    platforms: ['steam', 'gog', 'epic'],
    cover: null,
    tags: ['открытый мир', 'футуристика', 'dlc'],
    trailerId: '8X2kIfS6fb8',
    extraTrailers: [{ id: 'sJbexcm4Trk', label: 'Phantom Liberty' }],
    desc: 'Официальный текст и озвучка основной игры. Для Phantom Liberty — фанатские дубляжи (официально только субтитры).',
    translations: [
      { type: 'text', status: 'done', author: 'CD Projekt RED', rating: 4.8,
        name: 'Официальный перевод CDPR',
        body: '<p><strong>Что переведено:</strong> Весь основной сюжет и Phantom Liberty (текст и субтитры)</p><p><strong>Примечание:</strong> Русская озвучка основной игры есть, DLC Phantom Liberty — только субтитры.</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'DreamVoice', rating: 4.6, version: 'v5.3', updated: '2025-08',
        name: 'DreamVoice — Гибридный дубляж Phantom Liberty',
        body: '<p><strong>Статус:</strong> актуально на патч 2.3+</p><p><strong>Что озвучено:</strong> Полный дубляж DLC Phantom Liberty (гибрид: нейросеть и ручная доработка)</p><p><strong>Совместимость:</strong> Steam, GOG</p>',
        links: '<a href="https://www.playground.ru/cyberpunk_2077/file/cyberpunk_2077_gibridnyj_dublyazh_dlya_dlc_phantom_liberty_v1_0_5_3_dreamvoice-1691775" class="btn" target="_blank" rel="noopener">Playground</a><a href="https://t.me/DreamVoiceRu" class="btn" target="_blank" rel="noopener">Telegram</a>',
        install: '<details class="install"><summary>Краткая установка</summary><ol><li>Удалите предыдущие моды озвучки</li><li>Скачайте архив с Playground</li><li>Распакуйте в папку с игрой по инструкции из архива</li></ol></details>' },
      { type: 'voice', status: 'progress', author: 'GamesVoice', rating: 0, version: '—', updated: '2026-09',
        name: 'GamesVoice — Профессиональный дубляж Phantom Liberty',
        body: '<p><strong>Статус:</strong> В активной разработке</p><p><strong>Что планируется:</strong> Полный профессиональный дубляж с актёрами</p>',
        links: '<a href="https://gamesvoice.ru/library" class="btn" target="_blank" rel="noopener">GamesVoice</a>' },
      { type: 'voice', status: 'done', author: 'SynthVoiceRu', rating: 3.9, version: 'r12', updated: '2024-03',
        name: 'Нейро-дубляж SynthVoiceRu',
        body: '<p><strong>Что озвучено:</strong> Основная игра и DLC в разном качестве</p>',
        links: '<a href="https://www.playground.ru/cyberpunk_2077/file/cyberpunk_2077_nejro_dublyazh_dlya_dlc_phantom_liberty_v2_0_0_synthvoiceru-1683699" class="btn" target="_blank" rel="noopener">Playground</a>' }
    ]
  },
  {
    id: 'bg3',
    title: "Baldur's Gate 3",
    year: '2023',
    genre: 'CRPG',
    developer: 'Larian Studios',
    platforms: ['steam', 'gog', 'ps', 'xbox'],
    cover: null,
    tags: ['dnd', 'пошаговая', 'кооператив'],
    trailerId: '1T22wNvoNiU',
    desc: 'Официальный текст. Полной профессиональной озвучки нет — есть качественные нейросетевые варианты SynthVoiceRu.',
    translations: [
      { type: 'text', status: 'done', author: 'Larian Studios', rating: 4.5,
        name: 'Официальный перевод Larian',
        body: '<p><strong>Что переведено:</strong> Полный текстовый перевод и субтитры</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'SynthVoiceRu', rating: 4.7, version: '1.0 (SV2)', updated: '2024-12',
        name: 'SynthVoiceRu — Нейросетевой дубляж и закадр',
        body: '<p><strong>Что озвучено:</strong> Полный дубляж и отдельная закадровая версия (модель SV2)</p>',
        links: '<a href="https://www.playground.ru/baldurs_gate_3/file/baldurs_gate_3_russkaya_ozvuchka_nejrosetevoj_dublyazh_v1_0_synthvoiceru-1698229" class="btn" target="_blank" rel="noopener">Playground — дубляж</a><a href="https://www.playground.ru/baldurs_gate_3/file/baldurs_gate_3_rusifikator_zvuka_nejrosetevoj_zakadr_v1_0_synthvoiceru-1698264" class="btn" target="_blank" rel="noopener">Закадр</a>',
        install: '<details class="install"><summary>Краткая установка</summary><ol><li>Скачать файлы (3–4 архива)</li><li>Положить в папку Mods Larian (LocalAppData)</li><li>В настройках отключить озвучку реплик по клику</li></ol></details>' }
    ]
  },
  {
    id: 'hogwarts',
    title: 'Hogwarts Legacy',
    year: '2023',
    genre: 'Action-RPG',
    developer: 'Avalanche Software',
    platforms: ['steam', 'ps', 'xbox'],
    cover: null,
    tags: ['гарри поттер', 'открытый мир', 'магия'],
    trailerId: '1O6Qstncpnc',
    desc: 'Один из самых качественных фанатских дубляжей последних лет — GamesVoice.',
    translations: [
      { type: 'both', status: 'done', author: 'GamesVoice', rating: 4.9, version: '1.5', updated: '2026-09',
        name: 'GamesVoice — Полная локализация',
        body: '<p><strong>Что переведено:</strong> Текст, текстуры, полная профессиональная озвучка</p><p><strong>Актёры:</strong> Профессиональный состав студии</p>',
        links: '<a href="https://www.playground.ru/hogwarts_legacy/file/hogwarts_legacy_rusifikator_teksta_tekstur_i_zvuka_gamesvoice-1681716" class="btn" target="_blank" rel="noopener">Playground</a><a href="https://gamesvoice.ru/library" class="btn" target="_blank" rel="noopener">GamesVoice</a>',
        install: '<details class="install"><summary>Краткая установка</summary><ol><li>Скачать последнюю версию с Playground</li><li>Запустить установщик и указать папку с игрой</li></ol></details>' }
    ]
  },
  {
    id: 'eldenring',
    title: 'Elden Ring',
    subtitle: '+ Shadow of the Erdtree',
    year: '2022',
    genre: 'Action-RPG',
    developer: 'FromSoftware',
    platforms: ['steam', 'ps', 'xbox'],
    cover: null,
    tags: ['soulslike', 'открытый мир', 'dlc'],
    trailerId: 'E3Huy2cdih0',
    extraTrailers: [{ id: 'qLZenOn7WUo', label: 'Shadow of the Erdtree' }],
    desc: 'Официальной русской озвучки нет. Фанатские нейро-озвучки на Nexus и Playground.',
    translations: [
      { type: 'text', status: 'done', author: 'FromSoftware', rating: 4.3,
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Полностью, включая Shadow of the Erdtree. Озвучка только английская.</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'Сообщество / Nexus', rating: 4.0, version: '2.x', updated: '2025-05',
        name: 'Нейро-дубляж и моды озвучки',
        body: '<p><strong>Что озвучено:</strong> Реплики NPC и боссов</p>',
        links: '<a href="https://www.playground.ru/elden_ring/file/rus" class="btn" target="_blank" rel="noopener">Playground</a><a href="https://www.nexusmods.com/eldenring" class="btn" target="_blank" rel="noopener">Nexus Mods</a>',
        install: '<details class="install"><summary>Краткая установка</summary><ol><li>Установить Mod Engine 2</li><li>Следовать инструкции конкретного мода</li></ol></details>' }
    ]
  },
  {
    id: 'starfield',
    title: 'Starfield',
    subtitle: '+ Shattered Space',
    year: '2023',
    genre: 'Action-RPG',
    developer: 'Bethesda Game Studios',
    platforms: ['steam', 'gog', 'xbox'],
    cover: null,
    tags: ['космос', 'open world', 'bethesda'],
    trailerId: 'uMOPoAq5vIA',
    desc: 'Официальной русской озвучки нет. Сообщество делает текст и нейро-озвучку.',
    translations: [
      { type: 'text', status: 'done', author: 'Сообщество', rating: 4.2, version: '2.x', updated: '2025-04',
        name: 'Фанатский текстовый перевод',
        body: '<p><strong>Что переведено:</strong> Интерфейс, диалоги, квесты</p>',
        links: '<a href="https://www.playground.ru/starfield/file/rus" class="btn" target="_blank" rel="noopener">Playground — русики</a>' },
      { type: 'voice', status: 'progress', author: 'SynthVoiceRu', rating: 3.8, version: 'beta', updated: '2025-06',
        name: 'Нейро-озвучка',
        body: '<p><strong>Статус:</strong> В работе, покрытие растёт</p>',
        links: '<a href="https://www.playground.ru/starfield/file/rus" class="btn" target="_blank" rel="noopener">Playground — озвучки</a>' }
    ]
  },
  {
    id: 'stalker2',
    title: 'S.T.A.L.K.E.R. 2',
    subtitle: 'Heart of Chornobyl',
    year: '2024',
    genre: 'FPS / Survival',
    developer: 'GSC Game World',
    platforms: ['steam', 'xbox'],
    cover: null,
    tags: ['сталкер', 'зона', 'выживание'],
    trailerId: 'nAz9qlbl_8g',
    desc: 'Гибридные фанатские дубляжи — один из самых активных проектов локализации.',
    translations: [
      { type: 'text', status: 'done', author: 'GSC / сообщество', rating: 4.0,
        name: 'Официальный и улучшенный текст',
        body: '<p><strong>Что переведено:</strong> Текст и субтитры</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'Eloquence / Реплика / SynthVoice', rating: 4.3, version: '2.0', updated: '2026-01',
        name: 'Тройной гибридный дубляж',
        body: '<p><strong>Что озвучено:</strong> ~26 000 файлов: Реплика + Eloquence Studio + SynthVoice</p>',
        links: '<a href="https://www.playground.ru/stalker_2/file/s_t_a_l_k_e_r_2_rusifikator_zvuka_trojnoj_gibridnyj_dublyazh_eloquence_studio_replika_synthvoice-1817504" class="btn" target="_blank" rel="noopener">Playground — тройной дубляж</a><a href="https://www.playground.ru/stalker_2/file/rus" class="btn" target="_blank" rel="noopener">Все русики</a>',
        install: '<details class="install"><summary>Краткая установка</summary><ol><li>Скачать архив нужного варианта</li><li>Распаковать в Stalker2\\Content\\Paks\\~mods</li></ol></details>' }
    ]
  },
  {
    id: 'godofwar',
    title: 'God of War',
    subtitle: '2018',
    year: '2018',
    genre: 'Action-Adventure',
    developer: 'Santa Monica Studio',
    platforms: ['steam', 'ps'],
    cover: null,
    tags: ['мифология', 'экшен', 'сюжет'],
    trailerId: 'K0u_kAWLJOA',
    desc: 'Официальный текст. Полная профессиональная озвучка от GamesVoice.',
    translations: [
      { type: 'text', status: 'done', author: 'Sony', rating: 4.4,
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Полный текст и субтитры</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'GamesVoice', rating: 4.8, version: 'финал', updated: '2024',
        name: 'GamesVoice — Полный дубляж',
        body: '<p><strong>Что озвучено:</strong> Полная профессиональная озвучка</p>',
        links: '<a href="https://gamesvoice.ru/library" class="btn" target="_blank" rel="noopener">GamesVoice</a><a href="https://www.playground.ru/god_of_war_2018/file/rus" class="btn" target="_blank" rel="noopener">Playground</a>' }
    ]
  },
  {
    id: 'resident4',
    title: 'Resident Evil 4',
    subtitle: 'Remake',
    year: '2023',
    genre: 'Survival Horror',
    developer: 'Capcom',
    platforms: ['steam', 'ps', 'xbox'],
    cover: null,
    tags: ['хоррор', 'ремейк', 'экшен'],
    trailerId: 'E69tQMKd0oA',
    desc: 'Официальный текст. Фанатские нейро- и любительские озвучки.',
    translations: [
      { type: 'text', status: 'done', author: 'Capcom', rating: 4.2,
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Текст и субтитры</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'Сообщество', rating: 3.9, version: '1.x', updated: '2025',
        name: 'Нейро и любительская озвучка',
        body: '<p><strong>Что озвучено:</strong> Основные диалоги</p>',
        links: '<a href="https://www.playground.ru/resident_evil_4_2023/file/rus" class="btn" target="_blank" rel="noopener">Playground</a><a href="https://www.nexusmods.com/residentevil42023" class="btn" target="_blank" rel="noopener">Nexus</a>' }
    ]
  },
  {
    id: 'horizon2',
    title: 'Horizon Forbidden West',
    year: '2022',
    genre: 'Action-RPG',
    developer: 'Guerrilla',
    platforms: ['steam', 'ps'],
    cover: null,
    tags: ['открытый мир', 'роботы'],
    trailerId: 'Lq594XmpPBg',
    desc: 'Официальный текст. Озвучка — фанатские проекты.',
    translations: [
      { type: 'text', status: 'done', author: 'Sony', rating: 4.3,
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Полный текст и субтитры</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'progress', author: 'Сообщество', rating: 0, version: '—', updated: '2025',
        name: 'Фанатская озвучка',
        body: '<p><strong>Статус:</strong> Ищите актуальные проекты на Playground</p>',
        links: '<a href="https://www.playground.ru/horizon_forbidden_west/file/rus" class="btn" target="_blank" rel="noopener">Playground</a>' }
    ]
  },
  {
    id: 'alanswake2',
    title: 'Alan Wake 2',
    year: '2023',
    genre: 'Survival Horror',
    developer: 'Remedy Entertainment',
    platforms: ['steam', 'epic', 'ps', 'xbox'],
    cover: null,
    tags: ['хоррор', 'детектив'],
    trailerId: 'dlQ3FeNu5Yw',
    desc: 'Официальный текст. GamesVoice сделали профессиональную озвучку.',
    translations: [
      { type: 'text', status: 'done', author: 'Remedy', rating: 4.4,
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Текст и субтитры</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'GamesVoice', rating: 4.7, version: 'финал', updated: '2025',
        name: 'GamesVoice — Полный дубляж',
        body: '<p><strong>Что озвучено:</strong> Профессиональная озвучка</p>',
        links: '<a href="https://gamesvoice.ru/library" class="btn" target="_blank" rel="noopener">GamesVoice</a><a href="https://www.playground.ru/alan_wake_2/file/rus" class="btn" target="_blank" rel="noopener">Playground</a>' }
    ]
  },
  {
    id: 'metaphor',
    title: 'Metaphor: ReFantazio',
    year: '2024',
    genre: 'JRPG',
    developer: 'Studio Zero / Atlus',
    platforms: ['steam', 'ps', 'xbox'],
    cover: null,
    tags: ['jrpg', 'фэнтези'],
    trailerId: 'pP6kU_T6JVE',
    desc: 'Официальный текст. Нейро-озвучка от сообщества.',
    translations: [
      { type: 'text', status: 'done', author: 'Atlus', rating: 4.1,
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Текст и субтитры</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'done', author: 'Сообщество', rating: 3.8, version: '1.x', updated: '2025',
        name: 'Нейро-озвучка',
        body: '<p><strong>Что озвучено:</strong> Диалоги</p>',
        links: '<a href="https://www.playground.ru/metaphor_refantazio/file/rus" class="btn" target="_blank" rel="noopener">Playground</a><a href="https://www.nexusmods.com/metaphorrefantazio" class="btn" target="_blank" rel="noopener">Nexus</a>' }
    ]
  },
  {
    id: 'hades2',
    title: 'Hades II',
    year: '2025',
    genre: 'Roguelike',
    developer: 'Supergiant Games',
    platforms: ['steam'],
    cover: null,
    tags: ['roguelike', 'мифология'],
    trailerId: '91t0qI6Z2kA',
    desc: 'Официальный текст. Фанатские проекты озвучки в работе.',
    translations: [
      { type: 'text', status: 'done', author: 'Supergiant', rating: 4.5,
        name: 'Официальный перевод',
        body: '<p><strong>Что переведено:</strong> Полный текст</p>',
        links: '<span class="link-muted">Уже в игре</span>' },
      { type: 'voice', status: 'progress', author: 'Сообщество', rating: 0, version: '—', updated: '2025',
        name: 'Фанатская озвучка',
        body: '<p><strong>Статус:</strong> В разработке / ищите на Playground</p>',
        links: '<a href="https://www.playground.ru/hades_2/file/rus" class="btn" target="_blank" rel="noopener">Playground</a>' }
    ]
  }
];
